---
seo_meta:
  name: 万象黑客马拉松智慧养老模拟后台
  description: 万象黑客马拉松智慧养老模拟后台
  keywords: []

# url_options:
#  host: 0.0.0.0:3000
#  protocol: http

admin:
  emails: ['hackathon2020t2@wanxiang-blockchain.github']
